name: Readme
on:
  push:
    branches: main
jobs:
  manual:
    name: Readme
    uses: emacscollective/workflows/.github/workflows/readme.yml@main
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
