#+SETUPFILE: ~/.emacs.d/org-styles/html/stylish_white.theme
#+TITLE: consult-projectile
#+AUTHOR: Marco Pawłowski
#+EMAIL: pawlowski.marco@gmail.com
#+OPTIONS: num:nil \n:t


* 
A package to incorporate projectile into consult.
This allows to choose a project, when none is selected or
choose a project buffer/file.

** Usage
Call function =consult-projectile=.
Narrow selection with /B/ for buffer, /F/ for file or
/P/ for project.


** Installation

*** Melpa
This package is available on Melpa.
[Thanks to Pierre-Yves Ritschard]

*** Straight
The straight way is with the following code:
#+begin_src emacs-lisp
(use-package consult-projectile
  :straight (consult-projectile :type git :host gitlab :repo "OlMon/consult-projectile" :branch "master"))
#+end_src

*** Directly
The direct way is to clone this repo into your load-path and require =consult-projectile=.

** Changes
*** 0.6
_Introduced variable:_
=consult-projectile-source-projectile-project-action=.
This allows to change the behavior after selecting a project.

One use case would be the following:
#+begin_src emacs-lisp
(defun set-buffer-local-project ()
  (interactive)
  (let ((consult-projectile-source-projectile-project-action (lambda (dir) (setq-local projectile-project-root dir))))
    (consult-projectile)))
#+end_src

This allows to set a not project related buffer be project related and
makes =consult-projectile= treat it as one.
